# name your project! project names should contain only lowercase characters
# and underscores. a good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# this setting configures which "profile" dbt uses for this project.
profile: 'default'

# these configurations specify where dbt should look for different types of files.
# the `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. you probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled sql files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# configuring models
# full documentation: https://docs.getdbt.com/docs/configuring-models

# in this example config, we tell dbt to build all models in the example/ directory
# as tables. these settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  jaffle_shop:
    marts:
      core:
        +materialized: view
      # +required_tests: {"relationship.*": 1}
    staging:
      +materialized: table
    # +required_tests: {"unique.*|not_null": 2}
  snowflake_spend:
    +enabled: true
    +schema: spend

## project level test configurations
tests:
  jaffle_shop:
    # +severity: warn
    +store_failures: true
    +schema: test_failures